FROM nginx:alpine

COPY . /usr/share/nginx/html

RUN cat > /etc/nginx/conf.d/default.conf <<EOF
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index frontend.html;

    location = / {
        try_files /frontend.html =404;
    }

    location = /dashboard {
        try_files /dashboard.html =404;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]