FROM nginx:alpine

COPY . /usr/share/nginx/html

RUN cat > /etc/nginx/conf.d/default.conf <<EOF
server {
    listen 3000;
    server_name localhost;

    root /usr/share/nginx/html;

    # 1. Trang chủ tự nhảy sang /map (URL cực sạch, không có / ở cuối)
    location = / {
        return 301 \$scheme://\$http_host/map;
    }

    # 2. Xử lý đường dẫn /map 
    # Nginx sẽ ngầm định lấy file index.html ra trả về mà không tự ý đổi URL
    location = /map {
        try_files /map/index.html =404;
    }

    # 3. Xử lý đường dẫn /dashboard
    location = /dashboard {
        try_files /dashboard/index.html =404;
    }

    # 4. Cấp phép tải các file tĩnh (CSS, JS)
    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]