spring:
  r2dbc:
    url: r2dbc:postgresql://db:5432/cyberthreat
    username: appuser
    password: apppass
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: attack-group
      auto-offset-reset: earliest
  sql:
    init:
      mode: always

geoip:
  database:
    path: /app/geoip/GeoLite2-City.mmdb